"""Auction services package.

Re-exports all service functions, classes, and constants for 100% backward
compatibility with `from auctions import services` and `from . import services`.
"""
import random

from .bidding import (
    place_bid,
)
from .calendar import (
    _round_robin,
    generate_calendar,
    standings,
)
from .common import (
    ERROR_LABELS,
    BidResult,
    Reject,
    SealedResult,
    _check_roster_limits,
    _credits_str,
    _normalize_increment,
    participates_in,
)
from .formation import (
    DEFAULT_MODULE,
    FORMATION_MODULES,
    _CLASSIC_LINES,
    _ROLE_LABELS_LONG,
    _default_module,
    _formation_saved,
    _is_mantra,
    _module_lines,
    _module_slots,
    _modules_for,
    _slot_accepts,
    _slot_role_class,
    formation_state,
    save_formation,
)
from .lifecycle import (
    _advance_continuous,
    _next_unsaturated_pending,
    _prev_target,
    _recompute_price,
    _record_unsold,
    _record_winner_spend,
    _role_saturated,
    _sale_to_undo,
    _undo_sale,
    adjust_timer,
    assign_player,
    backup_database_async,
    call_player,
    cancel_bid,
    close_auction,
    close_if_expired,
    finalize_expired,
    force_close_lot,
    listone_loaded,
    lot_had_bid,
    manual_step,
    pause_auction,
    release_player,
    reset_if_closed,
    resume_auction,
    set_auto_advance,
    start_auction,
    stuck_closed_lot,
)
from .queue import (
    _QUEUE_BAND,
    _RECOVERY_BAND,
    _ROLE_RANK_ACDP,
    _ROLE_RANK_PDCA,
    _is_role_grouped,
    _letter_key,
    _next_pending,
    _opening_price_for,
    _ordered_free_agents,
    _role_band,
    _role_jump_target,
    _role_rank_for_nav,
    _role_rank_map,
    _set_on_block,
    ALPHABET,
    build_queue,
    draw_letters,
    enqueue_released_player,
    exclude_queue_item,
    get_queue_preview,
    max_unsold_passes,
    postpone_queue_item,
    prioritize_queue_item,
)
from .contracts import (
    close_renewals,
    declare_renewals,
    expiring as expiring_contracts,
    min_years as contract_min_years,
    new_season,
    roll_contract,
    roll_renewal,
    set_contract,
)
from .trade import (
    cancel_trade,
    decide_trade,
    propose_trade,
    respond_trade,
    trade_window_status,
)
from .market import (
    delete_market_bid,
    get_participant_market_bids,
    market_release_refund,
    place_market_bid,
    plan_market_resolution,
    resolve_market_session,
    settle_market_tie,
    sync_market_schedule,
    undo_market_resolution,
)
from .scoring import (
    _serialisable_lines,
    compute_giornata,
    giornata_perf_map,
    lineup_io,
    score_participant_giornata,
)
from .sealed import (
    _SEALED_FIELDS,
    _clear_sealed,
    _open_sealed,
    _sealed_triggered,
    open_sealed_now,
    place_sealed_bid,
    resolve_sealed,
    sealed_can_take_part,
    sealed_envelopes,
    sealed_status,
    sealed_tick,
)
from .session import (
    _restore_pool,
    _snapshot_participant,
    _snapshot_pool,
    delete_auction,
    delete_league,
    league_overview,
    resume_session,
    save_session,
    snapshot_participants,
)
from .state import (
    _player_stats,
    _ticker_warning,
    roster_plan,
    serialize_bid,
    serialize_state,
)

__all__ = [
    # common
    "Reject",
    "ERROR_LABELS",
    "participates_in",
    "BidResult",
    "SealedResult",
    "_credits_str",
    "_check_roster_limits",
    "_normalize_increment",
    # bidding
    "place_bid",
    # sealed
    "_SEALED_FIELDS",
    "_sealed_triggered",
    "_open_sealed",
    "_clear_sealed",
    "sealed_envelopes",
    "sealed_can_take_part",
    "place_sealed_bid",
    "resolve_sealed",
    "sealed_tick",
    "open_sealed_now",
    "sealed_status",
    # contracts
    "roll_contract",
    "set_contract",
    "new_season",
    "declare_renewals",
    "roll_renewal",
    "close_renewals",
    "expiring_contracts",
    "contract_min_years",
    # trade
    "propose_trade",
    "respond_trade",
    "cancel_trade",
    "decide_trade",
    "trade_window_status",
    # market
    "place_market_bid",
    "delete_market_bid",
    "get_participant_market_bids",
    "market_release_refund",
    "plan_market_resolution",
    "resolve_market_session",
    "settle_market_tie",
    "sync_market_schedule",
    "undo_market_resolution",
    # queue
    "_ROLE_RANK_PDCA",
    "_ROLE_RANK_ACDP",
    "_QUEUE_BAND",
    "_RECOVERY_BAND",
    "_is_role_grouped",
    "_role_rank_map",
    "_role_band",
    "ALPHABET",
    "draw_letters",
    "_letter_key",
    "_ordered_free_agents",
    "build_queue",
    "_next_pending",
    "_role_rank_for_nav",
    "_role_jump_target",
    "_opening_price_for",
    "_set_on_block",
    "max_unsold_passes",
    "enqueue_released_player",
    "get_queue_preview",
    "prioritize_queue_item",
    "postpone_queue_item",
    "exclude_queue_item",
    # lifecycle
    "listone_loaded",
    "start_auction",
    "call_player",
    "set_auto_advance",
    "pause_auction",
    "resume_auction",
    "adjust_timer",
    "force_close_lot",
    "close_auction",
    "close_if_expired",
    "lot_had_bid",
    "finalize_expired",
    "stuck_closed_lot",
    "reset_if_closed",
    "_role_saturated",
    "_next_unsaturated_pending",
    "_advance_continuous",
    "_prev_target",
    "_sale_to_undo",
    "_undo_sale",
    "manual_step",
    "_record_winner_spend",
    "_record_unsold",
    "release_player",
    "assign_player",
    "cancel_bid",
    "_recompute_price",
    # session
    "league_overview",
    "delete_league",
    "delete_auction",
    "_snapshot_pool",
    "_restore_pool",
    "_snapshot_participant",
    "save_session",
    "snapshot_participants",
    "resume_session",
    # formation
    "FORMATION_MODULES",
    "DEFAULT_MODULE",
    "_ROLE_LABELS_LONG",
    "_CLASSIC_LINES",
    "_is_mantra",
    "_modules_for",
    "_default_module",
    "_module_slots",
    "_module_lines",
    "_slot_accepts",
    "_slot_role_class",
    "_formation_saved",
    "formation_state",
    "save_formation",
    # scoring
    "lineup_io",
    "giornata_perf_map",
    "_serialisable_lines",
    "score_participant_giornata",
    "compute_giornata",
    # calendar
    "_round_robin",
    "generate_calendar",
    "standings",
    # state
    "roster_plan",
    "_player_stats",
    "_ticker_warning",
    "serialize_state",
    "serialize_bid",
    "backup_database_async",
    "random",
]
