# Generated by Django 5.2.14 on 2026-05-31 21:48

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('starting_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('current_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('min_increment', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12)),
                ('quick_increments', models.CharField(default='10,50,100,500', max_length=100)),
                ('duration_seconds', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('LIVE', 'Live'), ('PAUSED', 'Paused'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('remaining_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=80)),
                ('access_code', models.CharField(blank=True, db_index=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('increment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('server_received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('accepted', models.BooleanField(default=False)),
                ('rejection_reason', models.CharField(blank=True, max_length=120)),
                ('cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.CharField(blank=True, max_length=120)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auction')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.participant')),
            ],
            options={
                'ordering': ['-server_received_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='best_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auctions.bid'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction', 'accepted', 'cancelled'], name='auctions_bi_auction_330557_idx'),
        ),
    ]
