# Generated by Django 5.2.14 on 2026-05-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='antisnipe_seconds',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
