# Generated by Django 5.2.14 on 2026-06-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_antisnipe_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='remaining_at_bid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
