# Generated by Django 5.2.14 on 2026-06-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_add_remaining_at_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='current_cycle',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bid',
            name='cycle',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
