# Generated by Django 5.2.14 on 2026-06-01 13:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_add_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=Decimal('500'), max_digits=10),
        ),
        migrations.AddField(
            model_name='participant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='participant',
            name='spent_credits',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
