# Generated by Django 5.2.14 on 2026-06-01 14:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_credits_and_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('role', models.CharField(choices=[('P', 'Portiere'), ('D', 'Difensore'), ('C', 'Centrocampista'), ('A', 'Attaccante')], default='A', max_length=1)),
                ('team', models.CharField(blank=True, max_length=80)),
                ('initial_price', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=8)),
            ],
            options={
                'ordering': ['role', 'name'],
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions', to='auctions.player'),
        ),
    ]
