# Generated by Django 5.2.14 on 2026-06-01 15:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_player_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='player',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster', to='auctions.participant'),
        ),
    ]
