# Generated by Django 5.2.14 on 2026-06-01 19:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_player_ownership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Lega', max_length=120)),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('500'), max_digits=10)),
                ('slots_p', models.PositiveIntegerField(default=3)),
                ('slots_d', models.PositiveIntegerField(default=8)),
                ('slots_c', models.PositiveIntegerField(default=8)),
                ('slots_a', models.PositiveIntegerField(default=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='mode',
            field=models.CharField(choices=[('NEW_FROM_ZERO', 'Asta da zero'), ('REPAIR_AUCTION', 'Asta di riparazione'), ('CONTINUOUS_LEAGUE', 'Fantacalcio continuativo'), ('RESUME_SAVED', 'Ripresa sessione salvata')], default='NEW_FROM_ZERO', max_length=20),
        ),
        migrations.AddField(
            model_name='auction',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='source_league_id',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='auction',
            name='source_site',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='participant',
            name='external_team_id',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Lega', max_length=120)),
                ('source_site', models.CharField(blank=True, max_length=40)),
                ('external_id', models.CharField(blank=True, max_length=60)),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('500'), max_digits=10)),
                ('slots_p', models.PositiveIntegerField(default=3)),
                ('slots_d', models.PositiveIntegerField(default=8)),
                ('slots_c', models.PositiveIntegerField(default=8)),
                ('slots_a', models.PositiveIntegerField(default=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions', to='auctions.league'),
        ),
        migrations.AddField(
            model_name='participant',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='auctions.league'),
        ),
        migrations.CreateModel(
            name='RosterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('participant_name', models.CharField(blank=True, max_length=80)),
                ('player_name', models.CharField(max_length=120)),
                ('player_role', models.CharField(blank=True, max_length=1)),
                ('action', models.CharField(choices=[('release', 'Svincolo'), ('assign', 'Assegnazione'), ('admin_release', 'Svincolo (admin)'), ('admin_assign', 'Assegnazione (admin)'), ('edit', 'Modifica')], max_length=20)),
                ('credits_delta', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('by_admin', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_logs', to='auctions.participant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AuctionCycleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.PositiveIntegerField(default=1)),
                ('winner_name', models.CharField(blank=True, max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('player_name', models.CharField(blank=True, max_length=120)),
                ('player_role', models.CharField(blank=True, max_length=1)),
                ('assigned', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.CharField(blank=True, max_length=80)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_results', to='auctions.auction')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_results', to='auctions.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_wins', to='auctions.participant')),
            ],
            options={
                'ordering': ['auction', 'cycle'],
                'constraints': [models.UniqueConstraint(fields=('auction', 'cycle'), name='uniq_auction_cycle_result')],
            },
        ),
    ]
