# Generated by Django 5.2.14 on 2026-06-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_leagueconfig_auction_imported_at_auction_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='enforce_limits',
            field=models.BooleanField(default=True),
        ),
    ]
