# Generated by Django 5.2.14 on 2026-06-01 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auction_enforce_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sessione', max_length=120)),
                ('mode', models.CharField(blank=True, max_length=20)),
                ('current_cycle', models.PositiveIntegerField(default=1)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='auctions.league')),
                ('source_auction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_sessions', to='auctions.auction')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='resumed_from_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumed_auctions', to='auctions.auctionsession'),
        ),
    ]
