# Generated by Django 5.2.14 on 2026-06-01 21:08

import secrets

from django.db import migrations, models


def backfill_tokens(apps, schema_editor):
    """Give every pre-existing row an unguessable public token."""
    for model_name in ("Auction", "Participant"):
        Model = apps.get_model("auctions", model_name)
        for obj in Model.objects.filter(public_token=""):
            obj.public_token = secrets.token_urlsafe(16)
            obj.save(update_fields=["public_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auctionsession_auction_resumed_from_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='public_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='participant',
            name='public_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.RunPython(backfill_tokens, migrations.RunPython.noop),
    ]
