# Generated by Django 5.2.14 on 2026-06-02 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auction_release_refund_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='queue_by_role',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='queue_mode',
            field=models.CharField(choices=[('call', 'A chiamata'), ('random', 'Ordine casuale'), ('alpha', 'Ordine alfabetico')], default='call', max_length=10),
        ),
        migrations.CreateModel(
            name='AuctionQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=1)),
                ('order', models.IntegerField(default=0)),
                ('done', models.BooleanField(default=False)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='auctions.auction')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auctions.player')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('auction', 'player')},
            },
        ),
    ]
