# Generated by Django 5.2.14 on 2026-06-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auction_flow_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='opening_price_mode',
            field=models.CharField(choices=[('quotazione', 'Quotazione (valore attuale)'), ('base_one', 'Base 1')], default='quotazione', max_length=12),
        ),
    ]
