# Generated by Django 5.2.14 on 2026-06-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auction_opening_price_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
    ]
