# Generated by Django 5.2.14 on 2026-06-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_player_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ext_id',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
    ]
