# Generated by Django 5.2.14 on 2026-07-06 14:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_formation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Stagione', max_length=120)),
                ('matchdays', models.PositiveIntegerField(default=38)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='auctions.league')),
            ],
        ),
        migrations.CreateModel(
            name='Giornata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'In programma'), ('OPEN', 'Formazioni aperte'), ('LOCKED', 'Bloccata'), ('SCORED', 'Calcolata')], default='SCHEDULED', max_length=10)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giornate', to='auctions.season')),
            ],
            options={
                'ordering': ['season', 'number'],
            },
        ),
        migrations.CreateModel(
            name='GiornataScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6)),
                ('goals', models.PositiveSmallIntegerField(default=0)),
                ('modificatore', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=4)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('giornata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='auctions.giornata')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giornata_scores', to='auctions.participant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('giornata', 'participant'), name='uniq_giornata_participant_score')],
            },
        ),
        migrations.CreateModel(
            name='PlayerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('goals', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('own_goals', models.PositiveSmallIntegerField(default=0)),
                ('pen_scored', models.PositiveSmallIntegerField(default=0)),
                ('pen_missed', models.PositiveSmallIntegerField(default=0)),
                ('pen_saved', models.PositiveSmallIntegerField(default=0)),
                ('goals_conceded', models.PositiveSmallIntegerField(default=0)),
                ('yellow', models.BooleanField(default=False)),
                ('red', models.BooleanField(default=False)),
                ('giornata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='auctions.giornata')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='auctions.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('giornata', 'player'), name='uniq_giornata_player_perf')],
            },
        ),
        migrations.AddConstraint(
            model_name='giornata',
            constraint=models.UniqueConstraint(fields=('season', 'number'), name='uniq_season_giornata'),
        ),
    ]
