# Generated by Django 5.2.14 on 2026-07-06 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_season_giornata_giornatascore_playerperformance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_goals', models.PositiveSmallIntegerField(default=0)),
                ('away_goals', models.PositiveSmallIntegerField(default=0)),
                ('home_points', models.PositiveSmallIntegerField(default=0)),
                ('away_points', models.PositiveSmallIntegerField(default=0)),
                ('computed', models.BooleanField(default=False)),
                ('away', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='auctions.participant')),
                ('giornata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='auctions.giornata')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='auctions.participant')),
            ],
            options={
                'ordering': ['giornata', 'id'],
            },
        ),
    ]
