# Generated by Django 5.2.14 on 2026-08-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_fixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionqueueitem',
            name='unsold_passes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
