# Generated by Django 5.2.14 on 2026-08-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auctionqueueitem_unsold_passes'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='slot_limits',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leagueconfig',
            name='slot_limits',
            field=models.BooleanField(default=True),
        ),
    ]
