# Generated by Django 5.2.14 on 2026-08-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_league_slot_limits_leagueconfig_slot_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='block_leader_rebid',
            field=models.BooleanField(default=True),
        ),
    ]
