# Generated by Django 5.2.14 on 2026-08-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_auction_block_leader_rebid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='manual_auto_advance',
            field=models.BooleanField(default=False),
        ),
    ]
