# Generated by Django 5.2.14 on 2026-08-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_auction_manual_auto_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='screen_timer_size',
            field=models.CharField(choices=[('s', 'Piccolo'), ('m', 'Medio'), ('l', 'Grande')], default='m', max_length=1),
        ),
    ]
