# Generated by Django 5.2.14 on 2026-08-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_auction_screen_name_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='cycle_break_seconds',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
