# Generated by Django 5.2.14 on 2026-08-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_auction_cycle_break_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='cycle_break_seconds',
            field=models.FloatField(default=4),
        ),
    ]
