# Generated by Django 5.2.14 on 2026-08-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_alter_auction_cycle_break_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='game_mode',
            field=models.CharField(choices=[('CLASSIC', 'Classic'), ('MANTRA', 'Mantra')], default='CLASSIC', max_length=8),
        ),
        migrations.AddField(
            model_name='league',
            name='slots_gk',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='league',
            name='slots_out',
            field=models.PositiveIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='player',
            name='fvm_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='mantra_roles',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='player',
            name='price_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
