# Generated by Django 5.2.14 on 2026-08-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_league_game_mode_league_slots_gk_league_slots_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueconfig',
            name='game_mode',
            field=models.CharField(default='CLASSIC', max_length=8),
        ),
        migrations.AddField(
            model_name='leagueconfig',
            name='slots_gk',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='leagueconfig',
            name='slots_out',
            field=models.PositiveIntegerField(default=22),
        ),
    ]
