# Generated by Django 5.2.13 on 2026-08-25 07:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_leagueconfig_game_mode_leagueconfig_slots_gk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='drawn_letters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auction',
            name='sealed_bids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='sealed_contenders',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='auction',
            name='sealed_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='sealed_floor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='auction',
            name='sealed_reveal',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='auction',
            name='sealed_round',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auction',
            name='sealed_seconds',
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.AddField(
            model_name='auction',
            name='sealed_threshold_a',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AddField(
            model_name='auction',
            name='sealed_threshold_c',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='auction',
            name='sealed_threshold_d',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='auction',
            name='sealed_threshold_p',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='auction',
            name='within_role_order',
            field=models.CharField(choices=[('quota', 'Quotazione (alto → basso)'), ('alpha', 'Alfabetico'), ('random', 'Casuale'), ('letter', 'Alfabetico da lettera estratta')], default='quota', max_length=10),
        ),
        migrations.CreateModel(
            name='SealedBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.PositiveIntegerField(default=1)),
                ('round', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sealed_bids_set', to='auctions.auction')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sealed_bids', to='auctions.participant')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auctions.player')),
            ],
            options={
                'ordering': ['-amount', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('auction', 'cycle', 'round', 'participant'), name='uniq_sealed_bid_per_round')],
            },
        ),
    ]
