# Generated by Django 5.2.17 on 2026-09-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_auction_drawn_letters_auction_sealed_bids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='unsold_policy',
            field=models.CharField(choices=[('role_end', 'Fine reparto (alla fine del proprio ruolo)'), ('auction_end', 'Giro di recupero (a fine asta, dopo tutti i ruoli)'), ('discard', 'Invenduto definitivo (nessun secondo passaggio)')], default='role_end', max_length=20),
        ),
    ]
