# Generated by Django 5.2.17 on 2026-09-22 09:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0036_auction_unsold_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Mercato di Riparazione', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Bozza (non visibile ai partecipanti)'), ('open', 'Aperto (consegna buste in corso)'), ('closed', 'Chiuso (in attesa di spoglio)'), ('resolved', 'Concluso (spoglio eseguito)')], default='draft', max_length=12)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('allow_conditional_release', models.BooleanField(default=True)),
                ('release_refund_mode', models.CharField(choices=[('purchase', 'Costo di acquisto'), ('current', 'Costo attuale (quotazione)'), ('none', 'Nessun rimborso')], default='purchase', max_length=10)),
                ('max_acquisitions_p', models.PositiveIntegerField(default=0)),
                ('max_acquisitions_d', models.PositiveIntegerField(default=0)),
                ('max_acquisitions_c', models.PositiveIntegerField(default=0)),
                ('max_acquisitions_a', models.PositiveIntegerField(default=0)),
                ('results_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_sessions', to='auctions.league')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'In attesa di spoglio'), ('won', 'Aggiudicato'), ('lost', 'Non aggiudicato'), ('tied', 'Pari merito (spareggio)'), ('cancelled', 'Annullato / Ritirato')], default='pending', max_length=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_bids', to='auctions.participant')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_bids', to='auctions.player')),
                ('release_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_in_market_bids', to='auctions.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.marketsession')),
            ],
            options={
                'ordering': ['priority', '-amount', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('session', 'participant', 'player'), name='uniq_market_bid_per_player')],
            },
        ),
    ]
