# Generated by Django 5.2.17 on 2026-09-26 09:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0038_participant_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="trades_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="league",
            name="trades_need_approval",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="rosterlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("release", "Svincolo"),
                    ("assign", "Assegnazione"),
                    ("admin_release", "Svincolo (admin)"),
                    ("admin_assign", "Assegnazione (admin)"),
                    ("edit", "Modifica"),
                    ("trade", "Scambio"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proposer_credits",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "receiver_credits",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "In attesa di risposta"),
                            ("accepted", "Accettato, in attesa di ratifica"),
                            ("completed", "Completato"),
                            ("rejected", "Rifiutato"),
                            ("cancelled", "Annullato"),
                            ("vetoed", "Bocciato dall'admin"),
                            ("failed", "Non eseguibile"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("status_note", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="auctions.league",
                    ),
                ),
                (
                    "proposer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades_proposed",
                        to="auctions.participant",
                    ),
                ),
                (
                    "proposer_players",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="auctions.player"
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades_received",
                        to="auctions.participant",
                    ),
                ),
                (
                    "receiver_players",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="auctions.player"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
