# Generated by Django 5.2.17 on 2026-09-26 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0039_trades"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Periodo scambi", max_length=80)),
                ("opens_at", models.DateTimeField()),
                ("closes_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["opens_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="marketbid",
            name="uniq_market_bid_per_player",
        ),
        migrations.AddField(
            model_name="league",
            name="trades_same_roles",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="budget_rule",
            field=models.CharField(
                choices=[
                    ("priority", "Ogni offerta entro il budget, poi conta la priorità"),
                    (
                        "total",
                        "Totale offerte entro il budget (si annullano dalla più alta)",
                    ),
                ],
                default="priority",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="max_bids",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="require_same_role_release",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="tie_break",
            field=models.CharField(
                choices=[
                    ("manual", "Decide l'admin (scelta o sorteggio)"),
                    ("first", "Vince chi ha inserito l'offerta per primo"),
                ],
                default="manual",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tradewindow",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trade_windows",
                to="auctions.league",
            ),
        ),
    ]
