# Generated by Django 5.2.17 on 2026-09-26 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0040_market_rules_trade_windows"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="contract_min2_price",
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name="league",
            name="contract_min3_price",
            field=models.PositiveIntegerField(default=800),
        ),
        migrations.AddField(
            model_name="league",
            name="contracts_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="league",
            name="renewals_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="league",
            name="season_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="player",
            name="contract_years",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="renewal_declared",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="rescinded_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="auctions.participant",
            ),
        ),
        migrations.CreateModel(
            name="ContractEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(blank=True, max_length=120)),
                ("participant_name", models.CharField(blank=True, max_length=80)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("contract", "Dado contratti"),
                            ("renewed", "Rinnovo (dado verde)"),
                            ("rescinded", "Rescissione (dado rosso)"),
                            ("not_renewed", "Non rinnovato"),
                            ("set", "Durata impostata dall'admin"),
                            ("season", "Nuova stagione"),
                        ],
                        max_length=12,
                    ),
                ),
                ("roll", models.SmallIntegerField(blank=True, null=True)),
                ("years", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("manual", models.BooleanField(default=False)),
                ("by_admin", models.BooleanField(default=False)),
                ("season", models.PositiveIntegerField(default=1)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_events",
                        to="auctions.league",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="auctions.participant",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="auctions.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
