# Generated by Django 5.2.17 on 2026-09-26 14:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0041_contracts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="league",
            name="contract_min2_price",
        ),
        migrations.RemoveField(
            model_name="league",
            name="contract_min3_price",
        ),
        migrations.AddField(
            model_name="league",
            name="contract_rules",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="league",
            name="gk_max_clubs",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="league",
            name="salary_cap_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="league",
            name="salary_cap_spend",
            field=models.CharField(
                choices=[
                    ("gross", "Lorda (somma degli acquisti)"),
                    ("net", "Netta (acquisti meno incassi da vendite e svincoli)"),
                ],
                default="gross",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="salary_rules",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="league",
            name="standings_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="tie_break",
            field=models.CharField(
                choices=[
                    ("manual", "Decide l'admin (scelta o sorteggio)"),
                    ("first", "Vince chi ha inserito l'offerta per primo"),
                    ("rebid", "Secondo sfoglio speciale tra le squadre in parità"),
                ],
                default="manual",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="CapPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.PositiveIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("summer", "Fase estiva"),
                            ("winter", "Fase invernale"),
                        ],
                        max_length=6,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cap_phases",
                        to="auctions.league",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CapEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("base", "Tetto base (classifica anno precedente)"),
                            ("winter", "Fondi invernali (classifica attuale)"),
                            ("lost", "Bonus giocatori persi"),
                            ("renewals", "Bonus rinnovi mancati"),
                            ("extra", "Extra salary cap (budget convertito)"),
                            ("manual", "Rettifica admin"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cap_entries",
                        to="auctions.participant",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="auctions.capphase",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DecreeAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.PositiveIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("mid", "Metà stagione"), ("final", "Fine stagione")],
                        max_length=5,
                    ),
                ),
                ("details", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decree_awards",
                        to="auctions.league",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeagueRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.PositiveIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("mid", "Metà stagione"), ("final", "Fine stagione")],
                        max_length=5,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Inserita dall'admin"),
                            ("app", "Classifica interna FantaManager"),
                            ("remote", "Letta dal sito di lega"),
                        ],
                        default="manual",
                        max_length=6,
                    ),
                ),
                ("order", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rankings",
                        to="auctions.league",
                    ),
                ),
            ],
            options={
                "ordering": ["-season", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="capphase",
            constraint=models.UniqueConstraint(
                fields=("league", "season", "kind"), name="uniq_cap_phase"
            ),
        ),
        migrations.AddConstraint(
            model_name="decreeaward",
            constraint=models.UniqueConstraint(
                fields=("league", "season", "kind"), name="uniq_decree_per_season_kind"
            ),
        ),
        migrations.AddConstraint(
            model_name="leagueranking",
            constraint=models.UniqueConstraint(
                fields=("league", "season", "kind"), name="uniq_ranking_per_season_kind"
            ),
        ),
    ]
