# Generated by Django 5.2.17 on 2026-09-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0042_economy_contract_rules"),
    ]

    operations = [
        migrations.CreateModel(
            name="UefaClubRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("norm_name", models.CharField(db_index=True, max_length=120)),
                ("country", models.CharField(blank=True, max_length=60)),
                ("position", models.PositiveIntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="player",
            name="abroad_compensation",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="abroad_list",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="left_club",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="player",
            name="left_rank_kind",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name="player",
            name="left_rank_pos",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="left_serie_a_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("contract", "Dado contratti"),
                    ("renewed", "Rinnovo (dado verde)"),
                    ("rescinded", "Rescissione (dado rosso)"),
                    ("not_renewed", "Non rinnovato"),
                    ("set", "Durata impostata dall'admin"),
                    ("season", "Nuova stagione"),
                    ("left", "Uscito dalla Serie A"),
                ],
                max_length=12,
            ),
        ),
    ]
