# Generated by Django 5.2.17 on 2026-09-26 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0043_left_serie_a"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="acquired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="loan_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loaned_out",
                to="auctions.participant",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="loan_sessions_left",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="renewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="kind",
            field=models.CharField(
                choices=[("definitive", "Definitivo"), ("loan", "Prestito")],
                default="definitive",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="loan_sessions",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
