# Generated by Django 5.2.17 on 2026-09-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0044_loans_sales"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="turn_order",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="auction",
            name="turn_skips",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
