# Generated by Django 5.2.17 on 2026-09-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0046_managed_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="coach_name",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="participant",
            name="founded",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="honours",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="participant",
            name="kit_away",
            field=models.ImageField(blank=True, null=True, upload_to="kits/"),
        ),
        migrations.AddField(
            model_name="participant",
            name="kit_home",
            field=models.ImageField(blank=True, null=True, upload_to="kits/"),
        ),
        migrations.AddField(
            model_name="participant",
            name="president_name",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="participant",
            name="short_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="participant",
            name="stadium",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="participant",
            name="stadium_capacity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
