# Generated by Django 5.2.17 on 2026-09-27 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0047_team_sheet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name="MailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("smtp", "SMTP personalizzato"),
                            ("gmail", "Gmail / Google Workspace"),
                            ("outlook", "Outlook / Microsoft 365"),
                            ("brevo", "Brevo (Sendinblue)"),
                            ("sendgrid", "SendGrid"),
                            ("mailgun", "Mailgun"),
                            ("aruba", "Aruba"),
                            ("console", "Solo log (non invia)"),
                        ],
                        default="smtp",
                        max_length=12,
                    ),
                ),
                ("host", models.CharField(blank=True, max_length=200)),
                ("port", models.PositiveIntegerField(default=587)),
                (
                    "security",
                    models.CharField(
                        choices=[
                            ("starttls", "STARTTLS"),
                            ("ssl", "SSL/TLS"),
                            ("none", "Nessuna"),
                        ],
                        default="starttls",
                        max_length=10,
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=200)),
                ("password", models.CharField(blank=True, max_length=300)),
                ("from_email", models.EmailField(blank=True, max_length=254)),
                (
                    "from_name",
                    models.CharField(blank=True, default="FantaManager", max_length=80),
                ),
                ("reply_to", models.EmailField(blank=True, max_length=254)),
                ("timeout", models.PositiveSmallIntegerField(default=15)),
                ("last_test_at", models.DateTimeField(blank=True, null=True)),
                ("last_test_ok", models.BooleanField(default=False)),
                ("last_test_error", models.CharField(blank=True, max_length=300)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Impostazioni posta",
                "verbose_name_plural": "Impostazioni posta",
            },
        ),
    ]
