# Generated by Django 5.2.17 on 2026-09-29 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0048_mail_settings_team_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='managed_leagues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='release_refund_mode',
            field=models.CharField(choices=[('purchase', 'Costo di acquisto'), ('current', 'Costo attuale (quotazione)'), ('none', 'Nessun rimborso'), ('lugnano_sept', 'Fantalugnano Settembre (100% estero/svincolato, o quotazione)'), ('lugnano_jan', 'Fantalugnano Gennaio (50% estero min quotaz, o quotazione)')], default='purchase', max_length=20),
        ),
        migrations.AlterField(
            model_name='marketsession',
            name='release_refund_mode',
            field=models.CharField(choices=[('purchase', 'Costo di acquisto'), ('current', 'Costo attuale (quotazione)'), ('none', 'Nessun rimborso'), ('lugnano_sept', 'Fantalugnano Settembre (100% estero/svincolato, o quotazione)'), ('lugnano_jan', 'Fantalugnano Gennaio (50% estero min quotaz, o quotazione)')], default='purchase', max_length=20),
        ),
    ]
