# Generated by Django 5.2.17 on 2026-09-29 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0049_league_admins_alter_auction_release_refund_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='stage',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='auction',
            name='release_refund_mode',
            field=models.CharField(choices=[('purchase', 'Costo di acquisto'), ('current', 'Costo attuale (quotazione)'), ('none', 'Nessun rimborso'), ('lugnano_sept', 'Riparazione Settembre (100% se estero/svincolato, altrimenti quotazione)'), ('lugnano_jan', 'Riparazione Gennaio (50% se estero, altrimenti quotazione)')], default='purchase', max_length=20),
        ),
        migrations.AlterField(
            model_name='marketsession',
            name='release_refund_mode',
            field=models.CharField(choices=[('purchase', 'Costo di acquisto'), ('current', 'Costo attuale (quotazione)'), ('none', 'Nessun rimborso'), ('lugnano_sept', 'Riparazione Settembre (100% se estero/svincolato, altrimenti quotazione)'), ('lugnano_jan', 'Riparazione Gennaio (50% se estero, altrimenti quotazione)')], default='purchase', max_length=20),
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('ROUND_ROBIN', 'Campionato (Scontri Diretti 1vs1)'), ('TOTAL_POINTS', 'Gran Premio (Somma Punti)'), ('BATTLE_ROYALE', 'Battle Royale (Tutti contro Tutti)'), ('KNOCKOUT', 'Coppa a Eliminazione (Tabellone)'), ('GROUPS_KNOCKOUT', 'Coppa a Gironi + Fase Finale'), ('SEASON_SPLIT', 'Torneo a Fasi (Apertura / Clausura)'), ('SUPERCOPPA', 'Supercoppa di Lega (Sfida Secca)')], default='ROUND_ROBIN', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='auctions.season')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='fixture',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='auctions.competition'),
        ),
    ]
