# Generated by Django 5.2.17 on 2026-09-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0050_fixture_stage_alter_auction_release_refund_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerperformance',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='live_source',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='live_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='giornata',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'In programma'), ('OPEN', 'Formazioni aperte'), ('LOCKED', 'Bloccata'), ('LIVE', 'Live in corso'), ('SCORED', 'Calcolata')], default='SCHEDULED', max_length=10),
        ),
    ]
