# Generated by Django 5.2.17 on 2026-09-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0051_playerperformance_is_live_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giornata',
            name='serie_a_matchday',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
