# Generated by Django 5.2.13 on 2026-09-29 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0051_playerperformance_is_live_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsession',
            name='session_type',
            field=models.CharField(choices=[('repair', 'Mercato di Riparazione (Buste)'), ('renewals', 'Mercato Rinnovi Contratti')], default='repair', max_length=20),
        ),
        migrations.CreateModel(
            name='MatchdayFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(default='4-3-3', max_length=10)),
                ('starter_ids', models.JSONField(blank=True, default=list)),
                ('bench_ids', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('giornata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchday_formations', to='auctions.giornata')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchday_formations', to='auctions.participant')),
            ],
            options={
                'ordering': ['giornata', 'participant'],
                'constraints': [models.UniqueConstraint(fields=('giornata', 'participant'), name='uniq_giornata_participant_formation')],
            },
        ),
    ]
