# Generated by Django 5.2.13 on 2026-09-29 20:37

import django.db.models.deletion
from django.db import migrations, models


def add_session_type_if_not_exists(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            cursor.execute(
                "ALTER TABLE auctions_marketsession ADD COLUMN IF NOT EXISTS session_type varchar(20) NOT NULL DEFAULT 'repair';"
            )
        elif connection.vendor == 'sqlite':
            cursor.execute("PRAGMA table_info(auctions_marketsession);")
            cols = [row[1] for row in cursor.fetchall()]
            if 'session_type' not in cols:
                cursor.execute(
                    "ALTER TABLE auctions_marketsession ADD COLUMN session_type varchar(20) NOT NULL DEFAULT 'repair';"
                )
        else:
            try:
                schema_editor.add_field(
                    apps.get_model('auctions', 'MarketSession'),
                    models.CharField(max_length=20, default='repair')
                )
            except Exception:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0051_playerperformance_is_live_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='marketsession',
                    name='session_type',
                    field=models.CharField(choices=[('repair', 'Mercato di Riparazione (Buste)'), ('renewals', 'Mercato Rinnovi Contratti')], default='repair', max_length=20),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_session_type_if_not_exists, migrations.RunPython.noop),
            ],
        ),
        migrations.CreateModel(
            name='MatchdayFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(default='4-3-3', max_length=10)),
                ('starter_ids', models.JSONField(blank=True, default=list)),
                ('bench_ids', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('giornata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchday_formations', to='auctions.giornata')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchday_formations', to='auctions.participant')),
            ],
            options={
                'ordering': ['giornata', 'participant'],
                'constraints': [models.UniqueConstraint(fields=('giornata', 'participant'), name='uniq_giornata_participant_formation')],
            },
        ),
    ]
