# Generated by Django 5.2.17 on 2026-09-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0052_giornata_serie_a_matchday'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsession',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='marketsession',
            name='session_type',
            field=models.CharField(choices=[('sealed_bids', 'Mercato a Buste Segrete'), ('free_agency', 'Mercato Libero Continuo (Svincolati Immediati)'), ('waiver_wire', 'Draft di Riparazione (Waiver a Turni)'), ('buyout_clause', 'Mercato con Clausole Rescisorie'), ('live_auction', 'Asta Live di Riparazione')], default='sealed_bids', max_length=20),
        ),
        migrations.AlterField(
            model_name='competition',
            name='kind',
            field=models.CharField(choices=[('ROUND_ROBIN', 'Campionato (Scontri Diretti 1vs1)'), ('TOTAL_POINTS', 'Gran Premio (Somma Punti)'), ('FORMULA_1', 'Formula 1 (Punti GP di Giornata)'), ('SURVIVAL', "Survival Cup (L'Uomo Morto)"), ('SWISS_LEAGUE', 'Nuova Champions a Girone Svizzero'), ('FANTA_DAVIS', 'Fanta-Davis a Coppie'), ('KNOCKOUT', 'Coppa a Eliminazione (Tabellone)'), ('GROUPS_KNOCKOUT', 'Coppa a Gironi + Fase Finale'), ('SEASON_SPLIT', 'Torneo a Fasi (Apertura / Clausura)'), ('SUPERCOPPA', 'Supercoppa di Lega (Sfida Secca)'), ('BATTLE_ROYALE', 'Battle Royale (Tutti contro Tutti)')], default='ROUND_ROBIN', max_length=20),
        ),
    ]
