# Generated by Django 5.2.13 on 2026-09-30 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0052_marketsession_session_type_matchdayformation'),
        ('auctions', '0053_marketsession_config_marketsession_session_type_and_more'),
    ]

    operations = [
    ]
