# Generated by Django 5.2.13 on 2026-09-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0054_merge_20260930_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketsession',
            name='session_type',
            field=models.CharField(choices=[('repair', 'Mercato di Riparazione (Buste)'), ('renewals', 'Mercato Rinnovi Contratti'), ('sealed_bids', 'Mercato a Buste Segrete'), ('free_agency', 'Mercato Libero Continuo (Svincolati Immediati)'), ('waiver_wire', 'Draft di Riparazione (Waiver a Turni)'), ('buyout_clause', 'Mercato con Clausole Rescisorie'), ('live_auction', 'Asta Live di Riparazione')], default='repair', max_length=20),
        ),
    ]
