# Generated by Django 5.2.17 on 2026-10-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0055_alter_marketsession_session_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="sealed_enforce_rules",
            field=models.BooleanField(default=True),
        ),
    ]
