# Generated by Django 5.2.17 on 2026-10-06 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0056_auction_sealed_enforce_rules"),
    ]

    operations = [
        migrations.CreateModel(
            name="Footballer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_id", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(db_index=True, max_length=120)),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("P", "Portiere"),
                            ("D", "Difensore"),
                            ("C", "Centrocampista"),
                            ("A", "Attaccante"),
                        ],
                        max_length=1,
                    ),
                ),
                ("age", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("number", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("photo_url", models.URLField(blank=True)),
                (
                    "club_api_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("club_name", models.CharField(blank=True, max_length=120)),
                ("club_logo", models.URLField(blank=True)),
                ("in_serie_a", models.BooleanField(db_index=True, default=True)),
                ("seen_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="player",
            name="footballer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="league_players",
                to="auctions.footballer",
            ),
        ),
    ]
