# Generated by Django 5.2.17 on 2026-10-07 13:58

from django.db import migrations, models


def tidy_season_names(apps, schema_editor):
    """«Stagione 2026/27 · Lega X» → «Stagione 2026/27»: the league is already
    shown next to it on every page."""
    Season = apps.get_model("auctions", "Season")
    for season in Season.objects.select_related("league"):
        suffix = f" · {season.league.name}" if season.league_id else ""
        if suffix and season.name.endswith(suffix):
            season.name = season.name[: -len(suffix)]
            season.save(update_fields=["name"])


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0058_clear_thirdparty_photo_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="formation",
            name="bench_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(tidy_season_names, migrations.RunPython.noop),
    ]
