# Generated by Django 5.2.18 on 2026-10-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0059_formation_bench_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketsession",
            name="budget_rule",
            field=models.CharField(
                choices=[
                    (
                        "priority",
                        "Ordine di preferenza: ogni offerta entro il budget, allo spoglio conta la priorità",
                    ),
                    (
                        "total",
                        "Totale cumulativo: la somma delle offerte entro il budget, quelle più alte in eccesso si annullano",
                    ),
                ],
                default="priority",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("repair", "Mercato di Riparazione (Buste)"),
                    ("renewals", "Mercato Rinnovi Contratti"),
                    ("sealed_bids", "Mercato a Buste Segrete"),
                    ("free_agency", "Mercato Libero Continuo (Free Agency)"),
                    ("waiver_wire", "Draft di Riparazione (Waiver Wire a Turni)"),
                    ("buyout_clause", "Mercato con Clausole Rescissorie"),
                    ("live_auction", "Asta Live di Riparazione"),
                ],
                default="repair",
                max_length=20,
            ),
        ),
    ]
