# Generated by Django 5.2.18 on 2026-10-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0060_alter_marketsession_budget_rule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="sala",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
