# Generated by Django 5.2.18 on 2026-10-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0061_mail_password_encrypted"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixture",
            name="away_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="fixture",
            name="home_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
