# Generated by Django 5.2.18 on 2026-10-08 15:19

import auctions.crypto
from django.db import migrations


def encrypt_existing(apps, schema_editor):
    """Passwords saved in clear before this: re-saving them encrypts them."""
    MailSettings = apps.get_model("auctions", "MailSettings")
    for cfg in MailSettings.objects.exclude(password=""):
        cfg.save(update_fields=["password"])


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0061_league_sala"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailsettings",
            name="password",
            field=auctions.crypto.EncryptedTextField(blank=True),
        ),
        migrations.RunPython(encrypt_existing, migrations.RunPython.noop),
    ]
