# Generated by Django 5.2.18 on 2026-10-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0062_fixture_totals"),
    ]

    operations = [
        migrations.AddField(
            model_name="formation",
            name="captain_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="formation",
            name="vice_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matchdayformation",
            name="captain_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matchdayformation",
            name="vice_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
