# Generated by Django 5.2.18 on 2026-10-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0063_formation_captain"),
    ]

    operations = [
        migrations.AddField(
            model_name="giornata",
            name="starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
