# Generated by Django 5.2.18 on 2026-10-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0068_voti_di_riferimento_taratura"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="ticker_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
