# Generated by Django 5.2.18 on 2026-10-09 14:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0069_auction_ticker_seen_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="email_opt_out_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AccountPrivacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("self_registered", models.BooleanField(default=False)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("pending_email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_name", models.CharField(blank=True, max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("impersonate", "Vedi come (Supervisor)"),
                            ("view_as", "Vedi come (squadra)"),
                            ("credentials", "Credenziali cambiate da un admin"),
                            ("export", "Export dei dati personali"),
                            ("email_removed", "Email della squadra tolta"),
                            ("unlink", "Account scollegato dalla squadra"),
                            ("unsubscribe", "Disiscrizione dalle email della lega"),
                            ("account_deleted", "Account eliminato"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_name", models.CharField(blank=True, max_length=150)),
                ("detail", models.CharField(blank=True, max_length=200)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="auctions.league",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LegalAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc",
                    models.CharField(
                        choices=[
                            ("privacy", "Informativa privacy"),
                            ("terms", "Termini d'uso"),
                            ("age", "Dichiarazione di età (almeno 14 anni)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("version", models.CharField(max_length=30)),
                (
                    "accepted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legal_acceptances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-accepted_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "doc"], name="auctions_le_user_id_d389d2_idx"
                    )
                ],
            },
        ),
    ]
