"""URL routing for the auctions app."""
from django.urls import path

from . import health, views

urlpatterns = [
    path("healthz/", health.healthz, name="healthz"),
    path("", views.portal_view, name="home"),
    path("login/", views.login_view, name="login"),
    path("register/", views.register_view, name="register"),
    path("logout/", views.logout_view, name="logout"),
    path("onboarding/", views.onboarding_view, name="onboarding"),
    path("supervisor/", views.supervisor_dashboard, name="supervisor_dashboard"),
    path("supervisor/impersonate/exit/", views.supervisor_impersonate_exit, name="supervisor_impersonate_exit"),
    path("supervisor/backup/download/", views.supervisor_backup_download, name="supervisor_backup_download"),
    path("portal/", views.home_portal, name="home_portal"),

    # Clean Sports Management Dashboard Routes
    path("dashboard/", views.admin_dashboard, name="dashboard"),
    path("dashboard/leghe/", views.admin_dashboard, {"hub": True}, name="dashboard_hub"),
    path("dashboard/<int:league_id>/", views.admin_dashboard, name="dashboard_league"),
    path("lega/<int:league_id>/", views.admin_dashboard, name="league_view"),
    path("dashboard/regia/<int:auction_id>/", views.admin_dashboard, name="dashboard_regia"),
    path("regia/<int:auction_id>/", views.admin_dashboard, name="regia_auction"),

    # Version & System Status API
    path("api/version/", views.version_status_api, name="api_version"),

    # Direct team actions in single-league console
    path("dashboard/team/<int:participant_id>/credits/", views.admin_adjust_team_credits, name="admin_adjust_team_credits"),
    path("dashboard/team/<int:participant_id>/pin/", views.admin_reset_team_pin, name="admin_reset_team_pin"),
    path("dashboard/team/assign-player/", views.admin_quick_assign_player, name="admin_quick_assign_player"),

    # Console & Regia Management Routes (Canonical /dashboard/)
    path("dashboard/", views.admin_dashboard, name="admin_dashboard"),
    path("dashboard/create/", views.admin_create_auction, name="admin_create_auction"),
    path("dashboard/<int:auction_id>/classifica/", views.admin_classifica_partial, name="admin_classifica_partial"),
    path("dashboard/<int:auction_id>/storico/", views.admin_storico_partial, name="admin_storico_partial"),
    path("dashboard/league/new/", views.admin_create_league, name="admin_create_league"),
    path("dashboard/setup/", views.admin_setup, name="admin_setup"),
    path("dashboard/setup/create/", views.admin_setup_create, name="admin_setup_create"),
    path("dashboard/setup/analyze/", views.admin_setup_analyze, name="admin_setup_analyze"),
    path("dashboard/setup/<int:league_id>/pronta/", views.admin_setup_done, name="admin_setup_done"),
    path("dashboard/wizard/", views.admin_auction_wizard, name="admin_auction_wizard"),
    path("dashboard/wizard/create/", views.admin_wizard_create, name="admin_wizard_create"),
    path("dashboard/players/search/", views.admin_player_search, name="admin_player_search"),
    path("dashboard/participants/<int:participant_id>/roster/", views.admin_participant_roster, name="admin_participant_roster"),
    path("dashboard/config/", views.admin_config, name="admin_config"),
    path("dashboard/config/action/", views.admin_config_action, name="admin_config_action"),
    path("dashboard/mail/", views.admin_mail_settings, name="admin_mail_settings"),
    path("dashboard/sessions/", views.admin_sessions, name="admin_sessions"),
    path("dashboard/sessions/resume-latest/", views.admin_resume_latest, name="admin_resume_latest"),
    path("dashboard/<int:auction_id>/save-session/", views.admin_save_session, name="admin_save_session"),
    path("dashboard/sessions/<int:session_id>/resume/", views.admin_resume_session, name="admin_resume_session"),
    path("dashboard/<int:auction_id>/build-queue/", views.admin_build_queue, name="admin_build_queue"),
    path("dashboard/<int:auction_id>/queue/", views.admin_queue_preview, name="admin_queue_preview"),
    path("dashboard/<int:auction_id>/queue/prioritize/", views.admin_queue_prioritize, name="admin_queue_prioritize"),
    path("dashboard/<int:auction_id>/queue/postpone/", views.admin_queue_postpone, name="admin_queue_postpone"),
    path("dashboard/<int:auction_id>/queue/exclude/", views.admin_queue_exclude, name="admin_queue_exclude"),
    path("dashboard/<int:auction_id>/call-player/", views.admin_call_player, name="admin_call_player"),
    path("dashboard/<int:auction_id>/step/", views.admin_manual_step, name="admin_manual_step"),
    path("dashboard/<int:auction_id>/announce/", views.admin_announce, name="admin_announce"),
    path("dashboard/<int:auction_id>/timer/", views.admin_adjust_timer, name="admin_adjust_timer"),
    path("dashboard/<int:auction_id>/force-close/", views.admin_force_close_lot, name="admin_force_close_lot"),
    path("dashboard/<int:auction_id>/turns/", views.admin_auction_turns, name="admin_auction_turns"),
    path("dashboard/<int:auction_id>/auto-advance/", views.admin_set_auto_advance, name="admin_set_auto_advance"),
    path("dashboard/<int:auction_id>/confirm-advance/", views.admin_confirm_advance, name="admin_confirm_advance"),
    path("dashboard/<int:auction_id>/bid-for/", views.admin_bid_for, name="admin_bid_for"),
    path("dashboard/<int:auction_id>/open-sealed/", views.admin_open_sealed, name="admin_open_sealed"),
    path("dashboard/<int:auction_id>/resolve-sealed/", views.admin_resolve_sealed, name="admin_resolve_sealed"),
    path("dashboard/<int:auction_id>/edit/", views.admin_edit_auction, name="admin_edit_auction"),
    path("dashboard/<int:auction_id>/<str:action>/", views.admin_control, name="admin_control"),
    path("dashboard/bid/<int:bid_id>/cancel/", views.admin_cancel_bid, name="admin_cancel_bid"),
    path("dashboard/logs/", views.admin_logs_tail, name="admin_logs_tail"),
    path("dashboard/fantapazz/", views.admin_fantapazz, name="admin_fantapazz"),
    path("dashboard/fantapazz/import-rose/", views.admin_fantapazz_import_rose, name="admin_fantapazz_import_rose"),
    path("dashboard/market/", views.admin_market_dashboard, name="admin_market_dashboard"),
    path("dashboard/market/buste/", views.admin_market_buste, name="admin_market_buste"),
    path("dashboard/market/buste/<int:session_id>/", views.admin_market_session, name="admin_market_session"),
    path("dashboard/market/scambi/", views.admin_market_trades, name="admin_market_trades"),
    path("dashboard/market/asta/", views.admin_market_repair, name="admin_market_repair"),
    path("dashboard/market/movimenti/", views.admin_market_moves, name="admin_market_moves"),
    path("dashboard/market/<int:session_id>/notify/", views.admin_market_notify, name="admin_market_notify"),
    path("dashboard/market/create/", views.admin_market_create, name="admin_market_create"),
    path("dashboard/market/<int:session_id>/status/", views.admin_market_status, name="admin_market_status"),
    path("dashboard/market/<int:session_id>/resolve/", views.admin_market_resolve, name="admin_market_resolve"),
    path("dashboard/market/<int:session_id>/delete/", views.admin_market_delete, name="admin_market_delete"),
    path("dashboard/market/<int:session_id>/tie/", views.admin_market_settle_tie, name="admin_market_settle_tie"),
    path("dashboard/market/<int:session_id>/undo/", views.admin_market_undo, name="admin_market_undo"),
    path("dashboard/market/<int:session_id>/rules/", views.admin_market_rules, name="admin_market_rules"),
    path("dashboard/market/<int:session_id>/verbale/", views.admin_print_buste_report, name="admin_print_buste_report"),
    path("dashboard/market/<int:session_id>/verbale/csv/", views.admin_export_buste_csv, name="admin_export_buste_csv"),
    path("dashboard/trades/settings/", views.admin_trade_settings, name="admin_trade_settings"),
    path("dashboard/trades/windows/add/", views.admin_trade_window_add, name="admin_trade_window_add"),
    path("dashboard/trades/windows/<int:window_id>/delete/", views.admin_trade_window_delete, name="admin_trade_window_delete"),
    path("dashboard/trades/<int:trade_id>/decide/", views.admin_trade_decide, name="admin_trade_decide"),
    path("dashboard/remote/", views.admin_remote_status, name="admin_remote_status"),
    path("dashboard/remote/console/", views.admin_remote_page, name="admin_remote_page"),
    path("dashboard/remote/qr.png", views.admin_remote_qr, name="admin_remote_qr"),
    path("dashboard/remote/start/", views.admin_remote_start, name="admin_remote_start"),
    path("dashboard/remote/stop/", views.admin_remote_stop, name="admin_remote_stop"),
    path("dashboard/quit/", views.admin_quit, name="admin_quit"),
    path("regia/unlock/", views.regia_unlock, name="regia_unlock"),
    path("dashboard/export/", views.admin_export, name="admin_export"),
    path("dashboard/export/xlsx/", views.admin_export_xlsx, name="admin_export_xlsx"),
    path("dashboard/export/csv/", views.admin_export_csv, name="admin_export_csv"),
    path("dashboard/export/leghe/", views.admin_export_leghe, name="admin_export_leghe"),
    path("dashboard/export/schede/", views.admin_export_team_sheets, name="admin_export_team_sheets"),
    path("dashboard/export/schede/stampa/", views.admin_print_team_sheets, name="admin_print_team_sheets"),
    path("dashboard/export/rinnovi/", views.admin_export_renewals, name="admin_export_renewals"),
    path("dashboard/export/rinnovi/stampa/", views.admin_print_renewals, name="admin_print_renewals"),
    path("dashboard/rose/schede/import/", views.admin_import_team_sheets, name="admin_import_team_sheets"),
    path("dashboard/players/", views.admin_players, name="admin_players"),
    path("dashboard/players/import/", views.admin_import_players, name="admin_import_players"),
    path("dashboard/players/photos/", views.admin_apply_photos, name="admin_apply_photos"),
    path("dashboard/players/stats/", views.admin_import_stats, name="admin_import_stats"),
    path("dashboard/rose/import/", views.admin_import_rose, name="admin_import_rose"),
    path("dashboard/players/<int:player_id>/delete/", views.admin_delete_player, name="admin_delete_player"),
    path("dashboard/players/<int:player_id>/release/", views.admin_release_player, name="admin_release_player"),
    path("dashboard/players/<int:player_id>/assign/", views.admin_assign_player, name="admin_assign_player"),
    path("dashboard/players/clear/", views.admin_clear_players, name="admin_clear_players"),
    path("dashboard/calciatori/", views.admin_footballers, name="admin_footballers"),
    path("dashboard/calciatori/aggiorna/", views.admin_footballers_sync, name="admin_footballers_sync"),
    path("dashboard/calciatori/<int:footballer_id>/ruoli/", views.admin_footballer_edit, name="admin_footballer_edit"),
    path("dashboard/leghe/<int:league_id>/lista-generale/", views.admin_league_default_listone,
         name="admin_league_default_listone"),
    path("dashboard/participants/", views.admin_participants, name="admin_participants"),
    path("dashboard/participants/create/", views.admin_create_participant, name="admin_create_participant"),
    path("dashboard/participants/<int:participant_id>/edit/", views.admin_edit_participant, name="admin_edit_participant"),
    path("dashboard/participants/<int:participant_id>/delete/", views.admin_delete_participant, name="admin_delete_participant"),
    path("dashboard/participants/<int:participant_id>/email/", views.admin_participant_email, name="admin_participant_email"),
    path("dashboard/participants/invite/", views.admin_invite_teams, name="admin_invite_teams"),
    path("dashboard/participants/<int:participant_id>/account/", views.admin_participant_account, name="admin_participant_account"),
    path("dashboard/participants/<int:participant_id>/scheda/", views.admin_participant_profile, name="admin_participant_profile"),
    path("participants/<int:participant_id>/qr.png", views.participant_qr, name="participant_qr"),

    # Legacy alias routes (support old bookmarks / tests)
    path("admin-auction/", views.admin_dashboard),
    path("admin-auction/create/", views.admin_create_auction),
    path("admin-auction/<int:auction_id>/classifica/", views.admin_classifica_partial),
    path("admin-auction/<int:auction_id>/storico/", views.admin_storico_partial),
    path("admin-auction/league/new/", views.admin_create_league),
    path("admin-auction/setup/", views.admin_setup),
    path("admin-auction/setup/create/", views.admin_setup_create),
    path("admin-auction/setup/analyze/", views.admin_setup_analyze),
    path("admin-auction/setup/<int:league_id>/pronta/", views.admin_setup_done),
    path("admin-auction/wizard/", views.admin_auction_wizard),
    path("admin-auction/wizard/create/", views.admin_wizard_create),
    path("admin-auction/players/search/", views.admin_player_search),
    path("admin-auction/participants/<int:participant_id>/roster/", views.admin_participant_roster),
    path("admin-auction/config/", views.admin_config),
    path("admin-auction/config/action/", views.admin_config_action),
    path("admin-auction/mail/", views.admin_mail_settings),
    path("admin-auction/sessions/", views.admin_sessions),
    path("admin-auction/sessions/resume-latest/", views.admin_resume_latest),
    path("admin-auction/<int:auction_id>/save-session/", views.admin_save_session),
    path("admin-auction/sessions/<int:session_id>/resume/", views.admin_resume_session),
    path("admin-auction/<int:auction_id>/build-queue/", views.admin_build_queue),
    path("admin-auction/<int:auction_id>/queue/", views.admin_queue_preview),
    path("admin-auction/<int:auction_id>/queue/prioritize/", views.admin_queue_prioritize),
    path("admin-auction/<int:auction_id>/queue/postpone/", views.admin_queue_postpone),
    path("admin-auction/<int:auction_id>/queue/exclude/", views.admin_queue_exclude),
    path("admin-auction/<int:auction_id>/call-player/", views.admin_call_player),
    path("admin-auction/<int:auction_id>/step/", views.admin_manual_step),
    path("admin-auction/<int:auction_id>/announce/", views.admin_announce),
    path("admin-auction/<int:auction_id>/timer/", views.admin_adjust_timer),
    path("admin-auction/<int:auction_id>/force-close/", views.admin_force_close_lot),
    path("admin-auction/<int:auction_id>/turns/", views.admin_auction_turns),
    path("admin-auction/<int:auction_id>/auto-advance/", views.admin_set_auto_advance),
    path("admin-auction/<int:auction_id>/confirm-advance/", views.admin_confirm_advance),
    path("admin-auction/<int:auction_id>/bid-for/", views.admin_bid_for),
    path("admin-auction/<int:auction_id>/open-sealed/", views.admin_open_sealed),
    path("admin-auction/<int:auction_id>/resolve-sealed/", views.admin_resolve_sealed),
    path("admin-auction/<int:auction_id>/edit/", views.admin_edit_auction),
    path("admin-auction/<int:auction_id>/<str:action>/", views.admin_control),
    path("admin-auction/bid/<int:bid_id>/cancel/", views.admin_cancel_bid),
    path("admin-auction/logs/", views.admin_logs_tail),
    path("admin-auction/fantapazz/", views.admin_fantapazz),
    path("admin-auction/fantapazz/import-rose/", views.admin_fantapazz_import_rose),
    path("admin-auction/market/", views.admin_market_dashboard),
    path("admin-auction/market/buste/", views.admin_market_buste),
    path("admin-auction/market/buste/<int:session_id>/", views.admin_market_session),
    path("admin-auction/market/scambi/", views.admin_market_trades),
    path("admin-auction/market/asta/", views.admin_market_repair),
    path("admin-auction/market/movimenti/", views.admin_market_moves),
    path("admin-auction/market/<int:session_id>/notify/", views.admin_market_notify),
    path("admin-auction/market/create/", views.admin_market_create),
    path("admin-auction/market/<int:session_id>/status/", views.admin_market_status),
    path("admin-auction/market/<int:session_id>/resolve/", views.admin_market_resolve),
    path("admin-auction/market/<int:session_id>/delete/", views.admin_market_delete),
    path("admin-auction/market/<int:session_id>/tie/", views.admin_market_settle_tie),
    path("admin-auction/market/<int:session_id>/undo/", views.admin_market_undo),
    path("admin-auction/market/<int:session_id>/rules/", views.admin_market_rules),
    path("admin-auction/trades/settings/", views.admin_trade_settings),
    path("admin-auction/trades/windows/add/", views.admin_trade_window_add),
    path("admin-auction/trades/windows/<int:window_id>/delete/", views.admin_trade_window_delete),
    path("admin-auction/trades/<int:trade_id>/decide/", views.admin_trade_decide),
    path("admin-auction/remote/", views.admin_remote_status),
    path("admin-auction/remote/console/", views.admin_remote_page),
    path("admin-auction/remote/qr.png", views.admin_remote_qr),
    path("admin-auction/remote/start/", views.admin_remote_start),
    path("admin-auction/remote/stop/", views.admin_remote_stop),
    path("admin-auction/quit/", views.admin_quit),
    path("admin-auction/export/", views.admin_export),
    path("admin-auction/export/xlsx/", views.admin_export_xlsx),
    path("admin-auction/export/csv/", views.admin_export_csv),
    path("admin-auction/export/leghe/", views.admin_export_leghe),
    path("admin-auction/export/schede/", views.admin_export_team_sheets),
    path("admin-auction/export/schede/stampa/", views.admin_print_team_sheets),
    path("admin-auction/export/rinnovi/", views.admin_export_renewals),
    path("admin-auction/export/rinnovi/stampa/", views.admin_print_renewals),
    path("admin-auction/rose/schede/import/", views.admin_import_team_sheets),
    path("admin-auction/players/", views.admin_players),
    path("admin-auction/players/import/", views.admin_import_players),
    path("admin-auction/players/photos/", views.admin_apply_photos),
    path("admin-auction/players/stats/", views.admin_import_stats),
    path("admin-auction/rose/import/", views.admin_import_rose),
    path("admin-auction/players/<int:player_id>/delete/", views.admin_delete_player),
    path("admin-auction/players/<int:player_id>/release/", views.admin_release_player),
    path("admin-auction/players/<int:player_id>/assign/", views.admin_assign_player),
    path("admin-auction/players/clear/", views.admin_clear_players),
    path("admin-auction/participants/", views.admin_participants),
    path("admin-auction/participants/create/", views.admin_create_participant),
    path("admin-auction/participants/<int:participant_id>/edit/", views.admin_edit_participant),
    path("admin-auction/participants/<int:participant_id>/delete/", views.admin_delete_participant),
    path("admin-auction/participants/<int:participant_id>/email/", views.admin_participant_email),
    path("admin-auction/participants/invite/", views.admin_invite_teams),
    path("admin-auction/participants/<int:participant_id>/account/", views.admin_participant_account),
    path("admin-auction/participants/<int:participant_id>/scheda/", views.admin_participant_profile),
    path("participants/<int:participant_id>/qr.png", views.participant_qr, name="participant_qr"),

    # Participant flow.
    path("join/", views.join, name="join"),
    path("bid/<int:auction_id>/", views.bid_page, name="bid"),
    path("release/<int:player_id>/", views.participant_release_player, name="participant_release_player"),
    path("watch/<int:auction_id>/toggle/", views.participant_watch_toggle, name="participant_watch_toggle"),
    path("watch/<int:auction_id>/search/", views.participant_watch_search, name="participant_watch_search"),
    path("watch/item/<int:watch_id>/", views.participant_watch_update, name="participant_watch_update"),

    # Product shell (mobile-first FantaManager app; session-participant identity).
    path("app/login/", views.app_login, name="app_login"),
    path("app/logout/", views.app_logout, name="app_logout"),
    path("app/", views.app_home, name="app_home"),
    path("app/rosa/", views.app_rosa, name="app_rosa"),
    path("app/formazione/", views.app_formazione, name="app_formazione"),
    path("app/live/", views.app_live, name="app_live"),
    path("app/lega/", views.app_lega, name="app_lega"),
    path("app/fixture/<int:fixture_id>/detail/", views.app_fixture_detail, name="app_fixture_detail"),
    path("dashboard/fixture/<int:fixture_id>/detail/", views.app_fixture_detail, name="admin_fixture_detail"),
    path("app/mercato/", views.app_mercato, name="app_mercato"),
    path("app/mercato/bid/", views.app_market_bid, name="app_market_bid"),
    path("app/mercato/bid/delete/", views.app_market_delete_bid, name="app_market_delete_bid"),
    path("app/mercato/free-agency/buy/", views.app_market_free_agency_buy, name="app_market_free_agency_buy"),
    path("app/mercato/buyout/execute/", views.app_market_buyout_execute, name="app_market_buyout_execute"),
    path("app/mercato/waiver/claim/", views.app_market_waiver_claim, name="app_market_waiver_claim"),
    path("app/mercato/waiver/delete/", views.app_market_waiver_delete, name="app_market_waiver_delete"),
    path("app/scambi/", views.app_scambi, name="app_scambi"),
    path("app/mercato/extra-cap/", views.app_extra_cap, name="app_extra_cap"),
    path("app/rosa/contratto/<int:player_id>/dado/", views.app_contract_roll, name="app_contract_roll"),
    path("app/rosa/contratto/<int:player_id>/u21/", views.app_contract_u21, name="app_contract_u21"),
    path("app/rosa/lista-ceduti/<int:player_id>/svincola/", views.app_list_release, name="app_list_release"),
    path("app/rosa/rinnovi/dichiara/", views.app_renewals_declare, name="app_renewals_declare"),
    path("app/rosa/rinnovi/<int:player_id>/dado/", views.app_renewal_roll, name="app_renewal_roll"),
    path("app/rosa/scheda/", views.app_print_team_sheet, name="app_print_team_sheet"),
    path("app/rosa/scheda/<int:participant_id>/", views.app_print_team_sheet, name="app_print_team_sheet_id"),
    path("app/rosa/scheda/<int:participant_id>/xlsx/", views.app_export_team_sheet_xlsx, name="app_export_team_sheet_xlsx"),
    path("app/mercato/rinnovi/report/", views.app_print_renewals, name="app_print_renewals"),
    path("app/mercato/rinnovi/report/xlsx/", views.app_export_renewals_xlsx, name="app_export_renewals_xlsx"),
    path("app/mercato/session/<int:session_id>/verbale/", views.app_print_buste_report, name="app_print_buste_report"),
    path("app/mercato/session/<int:session_id>/verbale/csv/", views.app_export_buste_csv, name="app_export_buste_csv"),
    path("dashboard/contracts/", views.admin_contracts, name="admin_contracts"),
    path("dashboard/season/", views.admin_season, name="admin_season"),
    path("dashboard/season/action/", views.admin_season_action, name="admin_season_action"),
    path("dashboard/competizioni/", views.admin_competitions, name="admin_competitions"),
    path("dashboard/competizioni/create/", views.admin_competition_create, name="admin_competition_create"),
    path("dashboard/competizioni/<int:comp_id>/regenerate/", views.admin_competition_regenerate, name="admin_competition_regenerate"),
    path("dashboard/competizioni/<int:comp_id>/delete/", views.admin_competition_delete, name="admin_competition_delete"),
    path("dashboard/giornate/", views.admin_giornate, name="admin_giornate"),
    path("dashboard/giornate/import/", views.admin_voti_import, name="admin_voti_import"),
    path("dashboard/giornate/live-sync/", views.admin_live_voti_sync, name="admin_live_voti_sync"),
    path("dashboard/giornate/live-consolidate/", views.admin_live_voti_consolidate, name="admin_live_voti_consolidate"),
    path("dashboard/giornate/blocca/", views.admin_giornata_lock, name="admin_giornata_lock"),
    path("dashboard/giornate/punteggi/", views.admin_giornata_manual_scores, name="admin_giornata_manual_scores"),
    path("dashboard/giornate/regole/", views.admin_scoring_rules, name="admin_scoring_rules"),
    path("dashboard/giornate/formazione/<int:participant_id>/", views.admin_formation_edit, name="admin_formation_edit"),
    path("app/giornate/", views.admin_giornate, name="app_giornate"),
    path("app/giornate/import/", views.admin_voti_import, name="app_voti_import"),
    path("app/giornate/live-sync/", views.admin_live_voti_sync, name="app_live_voti_sync"),
    path("app/giornate/live-consolidate/", views.admin_live_voti_consolidate, name="app_live_voti_consolidate"),
    path("app/giornate/blocca/", views.admin_giornata_lock, name="app_giornata_lock"),
    path("app/giornate/punteggi/", views.admin_giornata_manual_scores, name="app_giornata_manual_scores"),
    path("app/giornate/regole/", views.admin_scoring_rules, name="app_scoring_rules"),
    path("app/giornate/formazione/<int:participant_id>/", views.admin_formation_edit, name="app_formation_edit"),
    path("dashboard/contracts/action/", views.admin_contracts_action, name="admin_contracts_action"),

    path("admin-auction/contracts/", views.admin_contracts),
    path("admin-auction/season/", views.admin_season),
    path("admin-auction/season/action/", views.admin_season_action),
    path("admin-auction/competizioni/", views.admin_competitions),
    path("admin-auction/giornate/", views.admin_giornate),
    path("admin-auction/giornate/import/", views.admin_voti_import),
    path("admin-auction/contracts/action/", views.admin_contracts_action),
    path("app/scambi/proponi/", views.app_trade_propose, name="app_trade_propose"),
    path("app/scambi/<int:trade_id>/rispondi/", views.app_trade_respond, name="app_trade_respond"),
    path("app/scambi/<int:trade_id>/ritira/", views.app_trade_cancel, name="app_trade_cancel"),
    path("app/altro/", views.app_altro, name="app_altro"),
    path("app/calciatori/", views.app_footballers, name="app_footballers"),
    # The league admin's Regia inside the app (+ "Vedi come" a team).
    path("app/regia/", views.app_regia, name="app_regia"),
    path("app/regia/mercato/<int:session_id>/", views.app_regia_market_session, name="app_regia_market_session"),
    path("app/regia/scambi/", views.app_regia_trades, name="app_regia_trades"),
    path("app/regia/squadre/", views.app_regia_teams, name="app_regia_teams"),
    path("app/regia/vedi/<int:participant_id>/", views.app_view_as, name="app_view_as"),
    path("app/regia/vedi/esci/", views.app_view_as_exit, name="app_view_as_exit"),
    path("app/altro/pin/", views.app_update_pin, name="app_update_pin"),

    # Big screen.
    path("screen/<int:auction_id>/", views.screen, name="screen"),
]
