"""Views package for auctions.

Maintains 100% backward compatibility by re-exporting all view functions and
internal helpers previously defined in auctions/views.py.
"""
from .admin_config import (
    _after_resume,
    admin_config,
    admin_config_action,
    admin_resume_latest,
    admin_resume_session,
    admin_save_session,
    admin_sessions,
)
from .admin_dashboard import (
    admin_auction_turns,
    _break_seconds,
    _classifica_standings,
    _pint,
    admin_adjust_timer,
    admin_announce,
    admin_bid_for,
    admin_build_queue,
    admin_call_player,
    admin_cancel_bid,
    admin_classifica_partial,
    admin_confirm_advance,
    admin_control,
    admin_create_auction,
    admin_dashboard,
    admin_edit_auction,
    admin_force_close_lot,
    admin_logs_tail,
    admin_manual_step,
    admin_open_sealed,
    admin_queue_exclude,
    admin_queue_postpone,
    admin_queue_preview,
    admin_queue_prioritize,
    admin_resolve_sealed,
    admin_set_auto_advance,
    admin_storico_partial,
)
from .admin_exports import (
    _export_filename,
    _export_league,
    admin_export,
    admin_export_csv,
    admin_export_leghe,
    admin_export_xlsx,
)
from .admin_contracts import admin_contracts, admin_contracts_action
from .admin_team_sheets import (
    admin_export_renewals,
    admin_export_team_sheets,
    admin_import_team_sheets,
    admin_participant_profile,
    admin_print_renewals,
    admin_print_team_sheets,
)
from .admin_season import admin_season, admin_season_action
from .admin_competitions import (
    admin_competitions,
    admin_competition_create,
    admin_competition_regenerate,
    admin_competition_delete,
)
from .admin_voti import admin_giornate, admin_upload_voti, admin_voti_import, admin_live_voti_sync, admin_live_voti_consolidate
from .admin_mail import admin_mail_settings
from .admin_market import (
    admin_market_buste,
    admin_market_create,
    admin_market_dashboard,
    admin_market_moves,
    admin_market_notify,
    admin_market_repair,
    admin_market_session,
    admin_market_trades,
    admin_market_delete,
    admin_market_resolve,
    admin_market_rules,
    admin_market_settle_tie,
    admin_market_status,
    admin_market_undo,
    admin_trade_decide,
    admin_trade_settings,
    admin_trade_window_add,
    admin_trade_window_delete,
)
from .admin_fantapazz import (
    _fp_collect_synced_cookie,
    _fp_provider,
    _resolve_import_league,
    admin_fantapazz,
    admin_fantapazz_auth_status,
    admin_fantapazz_browser_login,
    admin_fantapazz_cookie_sync,
    admin_fantapazz_import_rose,
)
from .admin_participants import (
    admin_adjust_team_credits,
    admin_create_participant,
    admin_delete_participant,
    admin_edit_participant,
    admin_invite_teams,
    admin_participant_account,
    admin_participant_email,
    admin_participant_roster,
    admin_participants,
    admin_quick_assign_player,
    admin_reset_team_pin,
    participant_qr,
)
from .admin_players import (
    _ROSE_SOURCE_LABELS,
    _resolve_rose_league,
    admin_apply_photos,
    admin_assign_player,
    admin_clear_players,
    admin_delete_player,
    admin_import_players,
    admin_import_rose,
    admin_import_stats,
    admin_player_search,
    admin_players,
    admin_release_player,
)
from .admin_remote import (
    _current_port,
    admin_quit,
    admin_remote_page,
    admin_remote_qr,
    admin_remote_start,
    admin_remote_status,
    admin_remote_stop,
    regia_unlock,
)
from .admin_wizards import (
    _fp_rose_ready,
    _game_mode,
    _import_leghe_rose_into_league,
    _import_listone_into_league,
    _import_rose_into_league,
    _parse_listone_upload,
    _sealed_settings,
    _setup_wizard_context,
    admin_auction_wizard,
    admin_create_league,
    admin_setup,
    admin_setup_analyze,
    admin_setup_done,
    admin_setup_create,
    admin_wizard_create,
)
from .home import home_portal
from .app import (
    app_altro,
    app_formazione,
    app_home,
    app_lega,
    app_live,
    app_login,
    app_logout,
    app_market_bid,
    app_market_delete_bid,
    app_mercato,
    app_contract_roll,
    app_contract_u21,
    app_extra_cap,
    app_list_release,
    app_renewal_roll,
    app_renewals_declare,
    app_scambi,
    app_trade_cancel,
    app_trade_propose,
    app_trade_respond,
    app_rosa,
    app_update_pin,
    app_fixture_detail,
)
from .app_admin import app_regia, app_view_as, app_view_as_exit, league_admin_digest
from .bidder import (
    _auction_for_join,
    bid_page,
    join,
    participant_release_player,
    participant_watch_search,
    participant_watch_toggle,
    participant_watch_update,
)
from .common import (
    SESSION_AUCTION_KEY,
    SESSION_LEAGUE_KEY,
    _ROLE_LABELS,
    _app_active_auction,
    _app_ctx,
    _app_standings,
    _call_order,
    _flow_mode,
    _opening_price_mode,
    _refund_mode,
    _remember_auction,
    _session_participant,
    _within_role,
    broadcast_state,
    current_auction,
    current_league,
    participant_join_url,
    participant_lan_join_url,
    staff_member_required,
    target_league,
    version_status_api,
)
from .auth import (
    login_view,
    logout_view,
    onboarding_view,
    portal_view,
    register_view,
)
from .supervisor import (
    supervisor_backup_download,
    supervisor_dashboard,
    supervisor_impersonate_exit,
    supervisor_required,
)
from .screen import screen

__all__ = [
    # auth & onboarding
    "portal_view",
    "login_view",
    "register_view",
    "logout_view",
    "onboarding_view",
    # supervisor
    "supervisor_backup_download",
    "supervisor_dashboard",
    "supervisor_impersonate_exit",
    "supervisor_required",
    # common
    "staff_member_required",
    "participant_join_url",
    "participant_lan_join_url",
    "broadcast_state",
    "_refund_mode",
    "_opening_price_mode",
    "_flow_mode",
    "_call_order",
    "_within_role",
    "SESSION_AUCTION_KEY",
    "SESSION_LEAGUE_KEY",
    "_remember_auction",
    "target_league",
    "current_league",
    "current_auction",
    "_session_participant",
    "_ROLE_LABELS",
    "_app_active_auction",
    "_app_standings",
    "_app_ctx",
    # admin_dashboard
    "_classifica_standings",
    "admin_dashboard",
    "admin_classifica_partial",
    "admin_storico_partial",
    "admin_create_auction",
    "admin_edit_auction",
    "admin_control",
    "admin_build_queue",
    "admin_queue_preview",
    "admin_queue_prioritize",
    "admin_queue_postpone",
    "admin_queue_exclude",
    "admin_call_player",
    "admin_manual_step",
    "admin_set_auto_advance",
    "admin_confirm_advance",
    "admin_force_close_lot",
    "admin_open_sealed",
    "admin_resolve_sealed",
    "admin_adjust_timer",
    "admin_bid_for",
    "admin_announce",
    "admin_cancel_bid",
    "_pint",
    "_break_seconds",
    # admin_wizards
    "admin_auction_wizard",
    "admin_wizard_create",
    "admin_create_league",
    "admin_setup",
    "admin_setup_create",
    "admin_setup_analyze",
    "admin_setup_done",
    "_sealed_settings",
    "_game_mode",
    "_setup_wizard_context",
    "_import_rose_into_league",
    "_import_leghe_rose_into_league",
    "_parse_listone_upload",
    "_import_listone_into_league",
    "_fp_rose_ready",
    # admin_config
    "admin_config",
    "admin_config_action",
    "admin_sessions",
    "admin_save_session",
    "_after_resume",
    "admin_resume_session",
    "admin_resume_latest",
    # admin_fantapazz
    "admin_fantapazz",
    "admin_fantapazz_cookie_sync",
    "admin_fantapazz_auth_status",
    "admin_fantapazz_browser_login",
    "admin_fantapazz_import_rose",
    "_fp_provider",
    "_resolve_import_league",
    "_fp_collect_synced_cookie",
    # admin_players
    "admin_players",
    "admin_apply_photos",
    "admin_import_stats",
    "admin_import_players",
    "_ROSE_SOURCE_LABELS",
    "_resolve_rose_league",
    "admin_import_rose",
    "admin_delete_player",
    "admin_clear_players",
    "admin_release_player",
    "admin_assign_player",
    "admin_player_search",
    # admin_exports
    "_export_league",
    "_export_filename",
    "admin_export",
    "admin_export_xlsx",
    "admin_export_csv",
    "admin_export_leghe",
    # admin_participants
    "admin_participants",
    "admin_create_participant",
    "admin_edit_participant",
    "admin_delete_participant",
    "admin_adjust_team_credits",
    "admin_reset_team_pin",
    "admin_quick_assign_player",
    "participant_qr",
    "admin_participant_roster",
    "admin_participant_account",
    "admin_participant_email",
    "admin_invite_teams",
    # bidder
    "participant_release_player",
    "_auction_for_join",
    "join",
    "bid_page",
    "participant_watch_toggle",
    "participant_watch_update",
    "participant_watch_search",
    # admin_remote
    "_current_port",
    "admin_remote_status",
    "admin_remote_page",
    "admin_remote_qr",
    "admin_quit",
    "admin_remote_start",
    "admin_remote_stop",
    "regia_unlock",
    # screen
    "screen",
    # app
    "app_home",
    "app_rosa",
    "app_live",
    "app_lega",
    "app_mercato",
    "app_market_bid",
    "app_market_delete_bid",
    "app_scambi",
    "app_contract_roll",
    "app_contract_u21",
    "app_extra_cap",
    "app_list_release",
    "app_renewals_declare",
    "app_renewal_roll",
    "admin_auction_turns",
    "admin_contracts",
    "admin_contracts_action",
    "admin_season",
    "admin_season_action",
    "app_trade_propose",
    "app_trade_respond",
    "app_trade_cancel",
    "app_altro",
    # app_admin (Regia inside the app)
    "app_regia",
    "app_view_as",
    "app_view_as_exit",
    "league_admin_digest",
    "app_formazione",
    "app_login",
    "app_logout",
    "app_update_pin",
    "admin_mail_settings",
    # admin_market
    "admin_market_dashboard",
    "admin_market_buste",
    "admin_market_session",
    "admin_market_trades",
    "admin_market_repair",
    "admin_market_moves",
    "admin_market_notify",
    "admin_market_create",
    "admin_market_status",
    "admin_market_resolve",
    "admin_market_rules",
    "admin_market_delete",
    "admin_market_settle_tie",
    "admin_market_undo",
    "admin_trade_settings",
    "admin_trade_decide",
    "admin_trade_window_add",
    "admin_trade_window_delete",
    # home
    "home_portal",
    "version_status_api",
    # voti
    "admin_giornate",
    "admin_upload_voti",
    "admin_voti_import",
    "admin_live_voti_sync",
    "admin_live_voti_consolidate",
    # competitions
    "admin_competitions",
    "admin_competition_create",
    "admin_competition_regenerate",
    "admin_competition_delete",
]
